### ISSUE TITLE
Failure in compiling doublevadd_publisher

### ISSUE THREAD

**Issue by jasvinderkhurana** [Xilinx/KRS#74]
Hi,

I have tried to setup a fresh on new ubuntu machine and install KRS, but it is failing to compile at accelerated_doublevadd_publisher. I have used below steps:

```
Install new ubuntu image 22.04
Install Vitis 2022.1 tools

#Install ROS2 and Gazebo
sudo apt install ros-humble-desktop-full
sudo apt-get install ros-humble-gazebo-ros-pkgs



#Install KRS
sudo apt-get -y install curl build-essential libssl-dev git wget \
                          ocl-icd-* opencl-headers python3-vcstool \
                          python3-colcon-common-extensions python3-colcon-mixin \
                          kpartx u-boot-tools pv gcc-multilib
sudo apt-get -y install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
sudo apt-get install qemu-user-static
mkdir -p ~/krs_ws/src; cd ~/krs_ws

cat << 'EOF' > krs_humble.repos
repositories:  
  perception/image_pipeline:
    type: git
    url: https://github.com/ros-acceleration/image_pipeline
    version: ros2

  tracing/tracetools_acceleration:
    type: git
    url: https://github.com/ros-acceleration/tracetools_acceleration
    version: humble

  firmware/acceleration_firmware_kr260:
    type: zip
    url: https://github.com/ros-acceleration/acceleration_firmware_kr260/releases/download/v1.0.0/acceleration_firmware_kr260.zip

  acceleration/adaptive_component:
    type: git
    url: https://github.com/ros-acceleration/adaptive_component
    version: humble
  acceleration/ament_acceleration:
    type: git
    url: https://github.com/ros-acceleration/ament_acceleration
    version: humble
  acceleration/ament_vitis:
    type: git
    url: https://github.com/ros-acceleration/ament_vitis
    version: humble
  acceleration/colcon-hardware-acceleration:
    type: git
    url: https://github.com/colcon/colcon-hardware-acceleration
    version: main
  acceleration/ros2_kria:
    type: git
    url: https://github.com/ros-acceleration/ros2_kria
    version: main
  acceleration/ros2acceleration:
    type: git
    url: https://github.com/ros-acceleration/ros2acceleration
    version: humble
  acceleration/vitis_common:
    type: git
    url: https://github.com/ros-acceleration/vitis_common
    version: humble
  acceleration/acceleration_examples:
    type: git
    url: https://github.com/ros-acceleration/acceleration_examples
    version: main
EOF

vcs import src --recursive < krs_humble.repos
source /tools/Xilinx/Vitis/2022.1/settings64.sh  # source Xilinx tools
source /opt/ros/humble/setup.bash  # Sources system ROS 2 installation.

export PATH="/usr/bin":$PATH 
colcon build --merge-install


```

Below is the error occured:

![Screenshot from 2022-10-14 14-52-34](https://user-images.githubusercontent.com/18255874/195829404-7d59c11d-56d1-45c0-b5e0-b1c17421ac9a.png)

@vmayoral, can you please have a quick look at it.. 

PS: The KRS used to build earlier may be 1 month back, but is failing now.
